version: '3'
services:
  web:
    image: node:10
    command: "npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
      
    ports:
      - "8000:8000"
    networks:
      - base


networks:
  base:

volumes:
  db_data: